// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'AppBody': string;
  'AppHeader': string;
  'AppRoom': string;
  'AppTitle': string;
  'MessageBlob': string;
  'MessageForm': string;
  'MessageInput': string;
  'MessageList': string;
  'MessageWrapper': string;
  'Sender': string;
  'Sent': string;
  'UserForm': string;
  'UserInput': string;
  'UserItem': string;
  'Users': string;
  'UsersList': string;
  'UsersOnline': string;
  'active_users_block': string;
  'chat_block': string;
  'chat_container': string;
  'main': string;
  'nav': string;
  'test': string;
}
declare const cssExports: CssExports;
export = cssExports;
