// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'active_users_block': string;
  'active_users_block_title': string;
  'active_users_block_users': string;
  'box': string;
  'btn': string;
  'btn_primary': string;
  'btn_secondary': string;
  'button': string;
  'chat_block': string;
  'chat_container': string;
  'container': string;
  'd_flex': string;
  'error': string;
  'fixed_bottom': string;
  'input': string;
  'input_group': string;
  'login_screen': string;
  'message': string;
  'message_primary': string;
  'message_secondary': string;
  'messages_container': string;
  'nav': string;
  'nonActive': string;
  'user_item': string;
}
declare const cssExports: CssExports;
export = cssExports;
